# Generated by Django 4.1.1 on 2022-09-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_project_project_images_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='note',
            new_name='project_id',
        ),
    ]
